/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute, Route } from 'workbox-routing';
import { NetworkFirst, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

const PAGES_CACHE = 'pages-v1';
const CACHEABLE_PAGES = ['/offline', '/error', '/history'];

// Claim control immediately
self.skipWaiting();
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite (includes offline page)
precacheAndRoute(self.__WB_MANIFEST);

// Install event - cache offline, error, and history pages
self.addEventListener('install', (event: ExtendableEvent) => {
  console.log('[SW] Installing service worker');
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PAGES_CACHE);
      // Cache all cacheable pages
      for (const page of CACHEABLE_PAGES) {
        try {
          await cache.add(new Request(page, { cache: 'reload' }));
          console.log('[SW] Cached page:', page);
        } catch (err) {
          console.warn('[SW] Failed to cache page:', page, err);
        }
      }
    })()
  );
});

// Activate event - clean old caches
self.addEventListener('activate', (event: ExtendableEvent) => {
  console.log('[SW] Activating service worker');
  event.waitUntil(
    (async () => {
      // Clean old caches
      const cacheNames = await caches.keys();
      await Promise.all(
        cacheNames
          .filter(name => (name.startsWith('pages-') || name.startsWith('offline-')) && name !== PAGES_CACHE)
          .map(name => caches.delete(name))
      );
    })()
  );
});

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache images
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Network First strategy for API calls (don't cache API responses when offline)
registerRoute(
  /\/api\/.*/,
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
    ],
  })
);

// Custom navigation handler - redirect to offline page when offline
const navigationHandler = async (options: any) => {
  const { request } = options;
  const url = new URL(request.url);
  
  // Check if this is a cacheable page (offline, error, history)
  const isCacheablePage = CACHEABLE_PAGES.some(page => url.pathname === page || url.pathname.startsWith(page + '/'));
  
  try {
    // Try to get from network first with timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3000); // 3 second timeout
    
    const response = await fetch(request, { 
      signal: controller.signal,
      cache: 'no-cache'
    });
    clearTimeout(timeoutId);
    
    // Cache the response only for cacheable pages (offline, error, history)
    if (response.ok && isCacheablePage) {
      const cache = await caches.open(PAGES_CACHE);
      cache.put(request, response.clone());
    }
    
    return response;
  } catch (error) {
    // Network request failed or timed out
    console.log('[SW] Network failed for:', url.pathname);
    
    // For cacheable pages (offline, error, history), try to serve from cache
    if (isCacheablePage) {
      const cache = await caches.open(PAGES_CACHE);
      const cachedResponse = await cache.match(request);
      if (cachedResponse) {
        console.log('[SW] Serving from cache:', url.pathname);
        return cachedResponse;
      }
    }
    
    // For any page when offline, redirect to offline page
    console.log('[SW] Looking for offline page in caches...');
    
    // Try the pages cache first
    const pagesCache = await caches.open(PAGES_CACHE);
    const offlineResponse = await pagesCache.match('/offline');
    if (offlineResponse) {
      console.log('[SW] Serving offline page from', PAGES_CACHE);
      return offlineResponse;
    }
    
    // Search all caches as fallback
    const cacheNames = await caches.keys();
    console.log('[SW] Available caches:', cacheNames);
    
    for (const cacheName of cacheNames) {
      const cache = await caches.open(cacheName);
      const cachedOffline = await cache.match('/offline');
      if (cachedOffline) {
        console.log('[SW] Serving offline page from', cacheName);
        return cachedOffline;
      }
    }
    
    // Final fallback - return a basic offline HTML
    return new Response(`
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Offline - FileDuck</title>
        <style>
          body { font-family: system-ui, sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #1a1a2e; color: white; text-align: center; padding: 20px; }
          h1 { font-size: 2rem; margin-bottom: 1rem; }
          p { color: #888; margin-bottom: 2rem; }
          button { background: #667eea; color: white; border: none; padding: 12px 24px; border-radius: 8px; cursor: pointer; font-size: 1rem; }
          button:hover { background: #5a67d8; }
        </style>
      </head>
      <body>
        <h1>🦆 You're Offline</h1>
        <p>Check your internet connection and try again.</p>
        <button onclick="window.location.reload()">Retry</button>
      </body>
      </html>
    `, {
      status: 503,
      statusText: 'Service Unavailable',
      headers: new Headers({
        'Content-Type': 'text/html; charset=utf-8'
      })
    });
  }
};

// Register navigation route
const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/api/], // Don't handle API routes
});

registerRoute(navigationRoute);

// Listen for messages from the client
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
