/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Claim control immediately
self.skipWaiting();
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache images
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Network First strategy for API calls (don't cache API responses when offline)
registerRoute(
  /\/api\/.*/,
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
    ],
  })
);

// Custom navigation handler - redirect to offline page when offline
const navigationHandler = async (options: any) => {
  const { request } = options;
  const url = new URL(request.url);
  
  // Don't cache these pages - always try network
  const noCachePages = ['/history', '/offline'];
  const isNoCachePage = noCachePages.some(page => url.pathname === page || url.pathname.startsWith(page + '/'));
  
  try {
    // Try to get from network first
    const response = await fetch(request);
    return response;
  } catch (error) {
    // Network request failed
    
    // If trying to access a no-cache page while offline, show offline page
    if (isNoCachePage) {
      const cache = await caches.open('workbox-precache-v2-' + self.location.origin);
      const offlineResponse = await cache.match('/offline');
      if (offlineResponse) {
        return offlineResponse;
      }
    }
    
    // Try to get from cache first for other pages
    const cache = await caches.open('workbox-precache-v2-' + self.location.origin);
    let cachedResponse = await cache.match(request);
    
    // If not in cache and offline, serve the offline page
    if (!cachedResponse) {
      // Try to get the offline page from cache
      const offlineResponse = await cache.match('/offline');
      if (offlineResponse) {
        return offlineResponse;
      }
      
      // Fallback to index.html if offline page not cached
      const indexResponse = await cache.match('/');
      if (indexResponse) {
        return indexResponse;
      }
    }
    
    return cachedResponse || new Response('Offline - please check your connection', {
      status: 503,
      statusText: 'Service Unavailable',
      headers: new Headers({
        'Content-Type': 'text/html'
      })
    });
  }
};

// Register navigation route
const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/api/], // Don't handle API routes
});

registerRoute(navigationRoute);

// Listen for messages from the client
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
